# Generated by Django 5.2.1 on 2025-07-03 20:40

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleList',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('heading', models.CharField(blank=True, help_text='The displayed title for the portfolio', max_length=100)),
                ('intro', models.CharField(blank=True, help_text='A short introduction to the blog.', max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BlogEntry',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('article_title', models.CharField(blank=True, help_text='The title of the article (will appear on the list page)', max_length=255)),
                ('article_summary', models.CharField(blank=True, help_text='A short summary of the article (will be shown on the blog card)', max_length=255)),
                ('article_text', wagtail.fields.StreamField([('text', 0), ('image', 1), ('image_left', 2), ('image_right', 3)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.images.blocks.ImageBlock', [], {}), 2: ('wagtail.blocks.StructBlock', [[('image_left', 1), ('text_right', 0)]], {}), 3: ('wagtail.blocks.StructBlock', [[('text_left', 0), ('image_right', 1)]], {})})),
                ('article_image', models.ForeignKey(blank=True, help_text='Main article image (to be shown on the blog card)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
