# Generated by Django 5.2.1 on 2025-07-07 18:25

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogentry',
            name='article_text',
            field=wagtail.fields.StreamField([('text', 0), ('image', 3), ('image_left', 4), ('image_right', 5)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.images.blocks.ImageBlock', [], {}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('text-center', 'center'), ('text-start', 'left'), ('text-end', 'right')]}), 3: ('wagtail.blocks.StructBlock', [[('image', 1), ('alignment', 2)]], {}), 4: ('wagtail.blocks.StructBlock', [[('image_left', 1), ('text_right', 0)]], {}), 5: ('wagtail.blocks.StructBlock', [[('text_left', 0), ('image_right', 1)]], {})}),
        ),
    ]
