# Generated by Django 5.2.1 on 2025-07-16 18:19

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogentry_article_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogentry',
            name='article_text',
            field=wagtail.fields.StreamField([('text', 0), ('image', 4), ('image_left', 5), ('image_right', 6)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.images.blocks.ImageBlock', [], {}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('text-center', 'center'), ('text-start', 'left'), ('text-end', 'right')]}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 150, 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('image', 1), ('alignment', 2), ('photo_description', 3)]], {}), 5: ('wagtail.blocks.StructBlock', [[('image_left', 1), ('text_right', 0)]], {}), 6: ('wagtail.blocks.StructBlock', [[('text_left', 0), ('image_right', 1)]], {})}),
        ),
    ]
