# Generated by Django 5.2.1 on 2025-08-19 19:18

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_blogentry_article_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogentry',
            name='article_text',
            field=wagtail.fields.StreamField([('text', 0), ('image', 6), ('image_left', 7), ('image_right', 8), ('two_columns', 10)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.images.blocks.ImageBlock', [], {}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('text-center', 'center'), ('text-start', 'left'), ('text-end', 'right')]}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 150, 'required': False}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('w-50', '50%'), ('w-60', '60%'), ('w-70', '70%'), ('w-75', '75%'), ('w-80', '80%'), ('w-90', '90%'), ('w-100', '100%')]}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('rounded-0', 'Sharp'), ('rounded-2', 'Slightly Round'), ('rounded-4', 'Medium Round'), ('rounded-5', 'Very Round'), ('rounded-circle', 'Circle')]}), 6: ('wagtail.blocks.StructBlock', [[('image', 1), ('alignment', 2), ('photo_description', 3), ('image_width', 4), ('image_corners', 5)]], {}), 7: ('wagtail.blocks.StructBlock', [[('image_left', 1), ('text_right', 0)]], {}), 8: ('wagtail.blocks.StructBlock', [[('text_left', 0), ('image_right', 1)]], {}), 9: ('wagtail.blocks.BooleanBlock', (), {'required': False}), 10: ('wagtail.blocks.StructBlock', [[('text_block_left', 0), ('text_block_right', 0), ('center_headings', 9)]], {})}),
        ),
    ]
