# Generated by Django 5.2.1 on 2025-07-03 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_aboutpage_portfolio_homepage_home_subtitle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn URL')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub URL')),
                ('kaggle_url', models.URLField(blank=True, verbose_name='Kaggle URL')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
