# Generated by Django 5.2.1 on 2025-07-05 17:55

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_navigationsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='intro',
        ),
        migrations.AddField(
            model_name='homepage',
            name='content',
            field=wagtail.fields.StreamField([('ThreeCardPanel', 3)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageBlock', [], {}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('Orange', '#ac5625'), ('Beige', '#b48351'), ('Tan', '#b5aba6'), ('Brown', '#483a2b'), ('Gray', '#666666')]}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 15, 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('left_card_image', 0), ('left_card_color', 1), ('left_card_text', 2), ('center_card_image', 0), ('center_card_color', 1), ('center_card_text', 2), ('right_card_image', 0), ('right_card_color', 1), ('right_card_text', 2)]], {})}),
        ),
    ]
