# Generated by Django 5.2.1 on 2025-07-07 16:54

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_homepage_image_remove_homepage_intro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.fields.StreamField([('ThreeCardPanel', 4)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageBlock', [], {}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('#ac5625', 'Orange'), ('#b48351', 'Beige'), ('#b5aba6', 'Tan'), ('#483a2b', 'Brown'), ('#666666', 'Gray')]}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 20, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 25, 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('left_card_image', 0), ('left_card_color', 1), ('left_card_text', 2), ('center_card_image', 0), ('center_card_color', 1), ('center_card_text', 3), ('right_card_image', 0), ('right_card_color', 1), ('right_card_text', 2)]], {})}),
        ),
    ]
