# Generated by Django 5.2.1 on 2025-07-07 18:15

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_homepage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='about_text',
            field=wagtail.fields.StreamField([('text', 0), ('image', 3), ('image_left', 4), ('image_right', 5)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'bold', 'italic', 'ol', 'ul', 'hr', 'link', 'document-link', 'embed', 'code', 'blockquote']}), 1: ('wagtail.images.blocks.ImageBlock', [], {}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('text-center', 'center'), ('text-start', 'left'), ('text-end', 'right')]}), 3: ('wagtail.blocks.StructBlock', [[('image', 1), ('alignment', 2)]], {}), 4: ('wagtail.blocks.StructBlock', [[('image_left', 1), ('text_right', 0)]], {}), 5: ('wagtail.blocks.StructBlock', [[('text_left', 0), ('image_right', 1)]], {})}),
        ),
    ]
