# Generated by Django 5.2.1 on 2025-07-22 17:16

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_aboutpage_about_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='about_text',
            field=wagtail.fields.StreamField([('text', 0), ('image', 6), ('image_left', 7), ('image_right', 8)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'bold', 'italic', 'ol', 'ul', 'hr', 'link', 'document-link', 'embed', 'code', 'blockquote']}), 1: ('wagtail.images.blocks.ImageBlock', [], {}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('text-center', 'center'), ('text-start', 'left'), ('text-end', 'right')]}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 150, 'required': False}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('w-50', '50%'), ('w-60', '60%'), ('w-70', '70%'), ('w-75', '75%'), ('w-80', '80%'), ('w-90', '90%'), ('w-100', '100%')]}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('rounded-0', 'Sharp'), ('rounded-2', 'Slightly Round'), ('rounded-4', 'Medium Round'), ('rounded-5', 'Very Round'), ('rounded-circle', 'Circle')]}), 6: ('wagtail.blocks.StructBlock', [[('image', 1), ('alignment', 2), ('photo_description', 3), ('image_width', 4), ('image_corners', 5)]], {}), 7: ('wagtail.blocks.StructBlock', [[('image_left', 1), ('text_right', 0)]], {}), 8: ('wagtail.blocks.StructBlock', [[('text_left', 0), ('image_right', 1)]], {})}),
        ),
    ]
