# Generated by Django 5.2.1 on 2025-07-22 18:25

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_aboutpage_about_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='about_text',
            field=wagtail.fields.StreamField([('text', 0), ('image', 1), ('image_left', 2), ('image_right', 3), ('image_text', 9)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'bold', 'italic', 'ol', 'ul', 'hr', 'link', 'document-link', 'embed', 'code', 'blockquote']}), 1: ('wagtail.images.blocks.ImageBlock', [], {}), 2: ('wagtail.blocks.StructBlock', [[('image_left', 1), ('text_right', 0)]], {}), 3: ('wagtail.blocks.StructBlock', [[('text_left', 0), ('image_right', 1)]], {}), 4: ('wagtail.blocks.RichTextBlock', (), {}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'left'), ('right', 'right')]}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('col-3', '25%'), ('col-4', '33%'), ('col-6', '50%'), ('col-8', '66%'), ('col-9', '75%')]}), 7: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('rounded-0', 'Sharp'), ('rounded-2', 'Slightly Round'), ('rounded-4', 'Medium Round'), ('rounded-5', 'Very Round'), ('rounded-circle', 'Circle')]}), 8: ('wagtail.blocks.CharBlock', (), {'max_length': 150, 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('image', 1), ('text', 4), ('placement', 5), ('image_col_width', 6), ('image_corners', 7), ('photo_description', 8)]], {})}),
        ),
    ]
